# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:
  backend:
    image: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: back-end/Dockerfile
    networks:
      - internal
      - default
    ports:
      - 8080:80
      - 8082:443

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./data/nginx/conf.d/http.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  #certbot:
  #  container_name: certbot
  #  image: certbot/certbot:latest
  #  restart: unless-stopped
  #  volumes:
  #    - ./data/certbot/conf:/etc/letsencrypt
  #    - ./data/certbot/www:/var/www/certbot
  #  depends_on:
  #    - nginx
  # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    container_name: database
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=neko_hat
      - MYSQL_USER=neko_hat
      - MYSQL_PASSWORD=neko_hat
      - MYSQL_DATABASE=neko_hat
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true